server:
  port: 9527

image:
  file:
    suffixes:
      - png
      - jpeg
    host:
      http://localhost:9527


logging:
  level:
    org.springframework.web.servlet: info
    github.resources: debug
