server:
  port: 9527

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.10.15:3306/img?useUnicode=true&characterEncoding=utf-8
    username: xu
    password: xupengfei

image:
  file:
    suffixes:
      - png
      - jpeg
    host:
      http://localhost:9527

logging:
  level:
    org.springframework.web.servlet: debug
    github.resources: debug
